config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"

Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]

  constraints Monban::Constraints::SignedIn.new do
    root "locations#index", as: :dashboard
  end

  constraints Monban::Constraints::SignedOut.new do
    root "homes#show"
  end

  resources :locations, only: [:index, :show] do
    resources :categories, only: [:show] do
      resources :posts, only: [:new, :create]
    end
  end

  resources :posts, only: [:show, :destroy, :edit, :update] do
    resources :spam_flags, only: [:create]
  end

  namespace :admin do
    resource :dashboard, only: [:show]
    resources :locations, only: [:new, :create] do
      resources :categories, only: [:new, :create]
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
  belongs_to :location
  validates :name, presence: true
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :categories
  validates :name, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :spam_flags
  paginates_per 10 

  has_attached_file :image, styles: { medium: "300x300>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :body, presence: true
  validates :title, presence: true

  scope :flagged, -> {
    unscoped.
    select("posts.*, count(*) as flag_count").
    joins(:spam_flags).
    group("posts.id").
    order("flag_count DESC, posts.updated_at DESC")
  }

  default_scope { order("updated_at DESC") }

  def flagged_by?(user)
    spam_flags.exists?(user: user)
  end
end

app/models/spam_flag.rb
class SpamFlag < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :post_id, uniqueness: { scope: :user_id }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :spam_flags

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  def can_edit?(post)
    email == post.user.email || admin?
  end

  def flag(post)
    spam_flags.create(post: post)
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController

  def new
    @location = Location.find(params[:location_id])
    @category = Category.new
  end

  def create
    @location = Location.find(params[:location_id])
    @category = @location.categories.create(category_params)

    if @category.save
      redirect_to @location
    else
      render :new
    end
  end

  private

  def category_params
    params.
      require(:category).
      permit(:name)
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < AdminController
  def show
    @posts = Post.flagged
  end
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < AdminController
  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to locations_path
    else
      render :new
    end
  end

  private

  def location_params
    params.require(:location).permit(:name)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin

  def require_admin
    unless current_user.admin?
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  before_action :require_login

  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @location = Location.find(params[:location_id])
    @category = Category.find(params[:id])
    @posts = @category.posts.page(params[:page])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :require_login, only: [:show]

  def show
    @user = User.new
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
    @category = Category.find(params[:category_id])
    @location = Location.find(params[:location_id])
  end

  def create
    @location = Location.find(params[:location_id])
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to [@location, @post.category]
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to [post.category.location, post.category]
  end

  def edit
    @post = Post.find(params(:id))
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to [@post.category.location, @post.category, @post]
    else
      render :edit
    end
  end

  private

  def post_params
    params.
      require(:post).
      permit(:title, :body, :image).
      merge(category_id: params[:category_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path 
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/spam_flags_controller.rb
class SpamFlagsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    current_user.flag(post)

    redirect_to post
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end
  
  def show
    @posts = current_user.posts
  end

  private

  def user_params
    params.
      require(:user).
      permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/new.html.erb
<%= form_for [:admin, @location, @category] do |form|%>
  <div>
    Name <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/dashboards/show.html.erb
<h2>Posts Flagged as Spam</h2>

<% @posts.each do |post| %>
  <div>
    <%= link_to post.title, post %>
    (<%= pluralize post.flag_count, "flag" %>)
  </div>
<% end %>

app/views/admin/locations/new.html.erb
<h2>New Location</h2>

<%= form_for [:admin, @location] do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/application/_sign_in.html.erb
<%= form_for :session, url: session_path do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign in" %>
  </div>
<% end %>

app/views/application/_sign_in_form.html.erb
<%= form_for :session, url: session_path do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign in" %>
  </div>
<% end %>

app/views/application/_sign_up.html.erb
<%= form_for @user do |form| %>
  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/application/_sign_up_form.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/categories/show.html.erb
<%= link_to "New Post", new_location_category_post_path(@location, @category) %>

<h2><%= @category.name %></h2>

<% @posts.each do |post|%>
  <div>
    <%= link_to post.title, post %>
  </div>
<% end %>

<div>
  <%= paginate @posts %>
</div>

app/views/homes/show.html.erb
<h1> Welcome to Craigstr!</h1>
<p>Craigstr's the easiest way to find and create local listings. You can get rid of old furniture, buy a used boat, make a casual connection, or murder a stranger under false pretenses! You're going to love it!</p>
<div class="row">
  <div class="col-md-6">
    <h2>Sign In</h2>
    <%= render "sign_in" %>
  </div>
  <div class="col-md-6">
    <h2>Sign Up</h2>
    <%= render "sign_up" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Craigstr</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Craigstr", root_path , id: "logo" %>

          <% if signed_in? %>
            <nav class="nav pull-right">>
              <%= link_to "My Posts", current_user %>
                <% if current_user.admin? %>
                  <%= link_to "Moderate Spam", admin_dashboard_path %>
                <% end %>
              <%= link_to "Sign out", session_path, method: :delete %>
            </nav>
          <% end %>
        </div>
      </div>
    </header>

    <div class="container">
      <div class="center hero-unit">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/locations/_location.html.erb
<div>
  <%= link_to location.name, location %>
</div>

app/views/locations/index.html.erb
<% if current_user.admin? %>
  <%= link_to "New Location", new_admin_location_path %>
<% end %>

<h2>Locations</h2>

<%= render @locations %>

app/views/locations/show.html.erb
<% if current_user.admin? %>
  <%= link_to "New Category", new_admin_location_category_path(@location) %>
<% end %>

<div class="location-name">
  <%= @location.name %>
</div>

<div class="categories">
  <ul class="list-group">
    <% @location.categories.each do |category| %>
      <li class="list-group-item">  <%= link_to category.name, [@location, category] %> </li>
    <% end %>
  </ul>
</div>

app/views/posts/_form.html.erb
<div>
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div>
  <%= form.label :body %>
  <%= form.text_area :body %>
</div>

<div>
  <%= form.label :image %>
  <%= form.file_field :image %>
</div>

app/views/posts/_post.html.erb
<div class="post">
  <div class="post-title">
    <h3><%= post.title %></h3>
    <p>Posted by <%= post.user.email %></p>
  </div>

  <div class="post-spam-flag">
    <% if post.flagged_by?(current_user) %>
      <p>Thanks for flagging this post as spam.</p>
    <% else %>
      <%= link_to "Flag as spam", post_spam_flags_path(post), method: :post %>
    <% end %>
  </div>

  <div class="post-body">
    <p><%= post.body %></p>
    <% if post.image? %>
      <%= image_tag post.image.url(:medium) %>
    <% end %>
  </div>

  <div class="post-edit">
    <% if current_user.can_edit?(post) %>
      <%= link_to "Edit Post", post %>
      <%= link_to "Delete Post", post, method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<%= form_for([@location, @category, @post]) do |form| %>
  <%= render form %>
  <%= form.submit %>
<% end %>

app/views/posts/new.html.erb
<%= form_for([@location, @category, @post]) do |form| %>
  <%= render form %>
  <%= form.submit %>
<% end %>

app/views/posts/show.html.erb
<%= render @post %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= render "sign_up" %>

app/views/users/show.html.erb
<h1>Your Posts</h1>

<% @posts.each do |post| %>
  <div class="post-title">
    <%= link_to post.title, post %>
  </div>
<% end %>